In [49]:
import numpy as np
import pandas as pd
from scipy.cluster.vq import kmeans,vq,whiten
import seaborn as sns

In [45]:
data=np.matrix([np.random.randint(0,5,10),np.random.randint(5,10,10),np.random.randint(10,15,10)])
data

matrix([[ 3,  0,  0,  3,  4,  3,  4,  1,  1,  1],
        [ 8,  9,  9,  9,  6,  9,  5,  5,  7,  5],
        [10, 12, 10, 12, 10, 10, 12, 12, 12, 12]])

In [46]:
data=whiten(data)
data

array([[1.01904933, 0.        , 0.        , 0.80178373, 1.60356745,
        0.97049496, 1.12390297, 0.21997067, 0.22237479, 0.21997067],
       [2.71746488, 1.76504522, 2.00137315, 2.40535118, 2.40535118,
        2.91148488, 1.40487872, 1.09985336, 1.55662356, 1.09985336],
       [3.3968311 , 2.35339362, 2.22374795, 3.2071349 , 4.00891863,
        3.2349832 , 3.37170892, 2.63964807, 2.66849754, 2.63964807]])

In [47]:
cent,_=kmeans(data,3)
cent

array([[1.01904933, 0.        , 0.        , 0.80178373, 1.60356745,
        0.97049496, 1.12390297, 0.21997067, 0.22237479, 0.21997067],
       [3.3968311 , 2.35339362, 2.22374795, 3.2071349 , 4.00891863,
        3.2349832 , 3.37170892, 2.63964807, 2.66849754, 2.63964807],
       [2.71746488, 1.76504522, 2.00137315, 2.40535118, 2.40535118,
        2.91148488, 1.40487872, 1.09985336, 1.55662356, 1.09985336]])

In [48]:
clusters,_=vq(data,cent)
clusters


array([0, 2, 1])